In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("./Datasets/DataSet_54F_mfcc.csv")

In [3]:
def get_count_when(bus,turn,signal,congestion):
    if(bus==turn==signal==congestion==0):
        return [bus,turn,signal,congestion,1,
                df[(df.Is_Adhoc==1)].shape[0]]
    else:
        return [bus,turn,signal,congestion,0,
                df[(df.Is_Bus_stop==bus)&(df.Is_Turn==turn)&(df.Is_Signal==signal)&(df.Is_Congestion==congestion)&(df.Is_Adhoc==0)].shape[0]]

In [4]:
from itertools import product

In [5]:
comb_res=list(map(lambda l:get_count_when(*l),list(product([0,1],[0,1],[0,1],[0,1]))))

In [6]:
df_ven=pd.DataFrame(comb_res,columns=['bus','turn','signal','congestion','adhoc','count'])

In [8]:
df_ven

    bus  turn  signal  congestion  adhoc  count
0     0     0       0           0      1   1609
1     0     0       0           1      0    533
2     0     0       1           0      0     60
3     0     0       1           1      0     52
4     0     1       0           0      0    413
5     0     1       0           1      0    109
6     0     1       1           0      0     23
7     0     1       1           1      0     10
8     1     0       0           0      0    737
9     1     0       0           1      0    148
10    1     0       1           0      0    115
11    1     0       1           1      0     22
12    1     1       0           0      0    438
13    1     1       0           1      0    123
14    1     1       1           0      0      3
15    1     1       1           1      0      1

In [9]:
df_ven.to_csv("./logs/ven_diagram_table.csv",index=False)